/*
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/
#include <iostream>
#include <vector>
#include <set>

std::vector<int> factor(int a)
{
    const int primes[] = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97};
    std::vector<int> v;
    for (auto p : primes)
    {
        int k = 0;
        while (a % p == 0)
        {
            k++;
            a /= p;
        }
        v.push_back(k);
    }
    return v;
}

std::vector<int> scale(const std::vector<int> &v, int a)
{
    auto w = std::vector<int>(v.size());
    for (uint i = 0; i < v.size(); i++)
        w[i] = a * v[i];
    return w;
}

int main()
{
    std::set<std::vector<int>> S;
    for (int a = 2; a <= 100; a++)
    {
        auto v = factor(a);
        for (int b = 2; b <= 100; b++)
            S.insert(scale(v, b));
    }
    std::cout << S.size() << std::endl;
}
