/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/
#include <iostream>

int main()
{
    uint64_t t = 1, p = 1, h = 1, T = 1, P = 1, H = 1;
    while (!(T == P && P == H) || T <= 40755)
    {
        if (T <= std::min(P, H))
            ++t, T = t * (t + 1) / 2;
        else if (P <= std::min(T, H))
            p++, P = p * (3 * p - 1) / 2;
        else
            h++, H = h * (2 * h - 1);
    }
    std::cout << T << std::endl;
}